-- AlterTable
ALTER TABLE `badservers` MODIFY `type` ENUM('CHEATING', 'LEAKING', 'RESELLING', 'ADVERTISING', 'OTHER') NOT NULL;

-- AlterTable
ALTER TABLE `imports` MODIFY `type` ENUM('OTHER', 'LEAKER', 'CHEATER', 'SUPPORTER', 'OWNER', 'BOT') NOT NULL;

-- AlterTable
ALTER TABLE `users` ADD COLUMN `reason` VARCHAR(191) NULL,
    MODIFY `type` ENUM('OTHER', 'LEAKER', 'CHEATER', 'SUPPORTER', 'OWNER', 'BOT') NOT NULL;
